# Generated by Django 4.2.6 on 2023-11-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(verbose_name='Horario')),
                ('confirmado', models.BooleanField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Exibicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=255, verbose_name='Tópico')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('alunos', models.ManyToManyField(to='projetoApp.aluno', verbose_name='Aluno')),
                ('professores', models.ManyToManyField(to='projetoApp.professor', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailDst', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField(verbose_name='Horario')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.inscricao')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmissao', models.DateField(verbose_name='Data Emissão')),
                ('codigo', models.CharField(blank=True, max_length=255, verbose_name='Código')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAvaliacacao', models.DateField(verbose_name='Data Avaliação')),
                ('descricao', models.TextField(verbose_name='Decrição')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.aluno')),
                ('exibicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoApp.exibicao')),
            ],
        ),
    ]
