# Generated by Django 4.2.6 on 2023-11-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0002_inscricao_exibicao_convite_checkin_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
