# Generated by Django 4.2.6 on 2023-11-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
