# Generated by Django 4.2.16 on 2025-08-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0007_delete_convite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetoApp.aluno', to_field='usuario_ptr_id'),
        ),
    ]
