# Generated by Django 4.2.6 on 2023-11-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0007_remove_evento_horario_evento_bairro_evento_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='harario_fim',
            new_name='horario_fim',
        ),
    ]
