# Generated by Django 4.2.6 on 2023-11-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0009_evento_ativo_exibicao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projetoApp.evento'),
        ),
    ]
