# Generated by Django 4.2.6 on 2023-11-21 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0011_alter_inscricao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetoApp.evento'),
        ),
    ]
