# Generated by Django 4.2.6 on 2023-11-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0013_alter_inscricao_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='exibicao',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetoApp.evento'),
        ),
    ]
