# Generated by Django 4.2.6 on 2023-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0014_exibicao_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exibicao',
            name='alunos',
            field=models.ManyToManyField(to='projetoApp.aluno', verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='exibicao',
            name='professores',
            field=models.ManyToManyField(to='projetoApp.professor', verbose_name='Professores'),
        ),
    ]
