# Generated by Django 4.2.6 on 2023-12-05 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoApp', '0016_rename_dataavaliacacao_avaliacao_dataavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exibicao',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today, verbose_name='Data Criação'),
        ),
    ]
